### PR TITLE
add headers params support

### PR DESCRIPTION
**Pull request by aguillem**
Add a little code snippet to allow sending headers params on ajax call

### CODE REVIEW

**Comment by Serhioromano** [comment]
This is cool feature. But I think you need to set header parameter in default parameters aray. Then you do not need to check if header is set you just pass it through.

Also add a comment to that parameter how to pass headers. Should it be array or object? WHat is format?

1. add header to `var defaults = {....` with extensive comment
2. Change code. No need for `if` any more. Just set `headers:this.options.headers`

**Comment by aguillem** [comment]
Thanks for your return.
I will correct that soon and pull request again.

**Comment by Serhioromano** [comment]
Perfect. I am here now.

**Comment by aguillem** [comment]
sorry for the response time, now it's done :)

**Comment by aguillem** [comment]
ohh damn, i've tried to rebase my branch but, as i'm new on git, i don't know if i do it properly or if i broke some things. sorry

**Comment by Serhioromano** [comment]
there is some broken things. I'll comment on those. Also there are changes like tabs. Would be good if there are no such changes. Because in long list of changes hard to track what was really changed and what just changed indent.

**Comment by aguillem** [comment]
I create a new branch and do a new pull request

**Pull request closed without merging**
