### PR TITLE
Created file es-DO.js

### PR DESCRIPTION
**Pull request by joenilson**
Added file translation for Dominican Republic

### CODE REVIEW

**Comment by Serhioromano** [comment]
Please add it to demo `index.html`

**Comment by Serhioromano** [comment]
You forgot to include your language file to the page. Also there is another index.html for Bootstrap 3 example.

**Comment by joenilson** [comment]
Hi, sorry, i has not used the demo html files, i added the i18n js file and updated index.html and index-bs3.html

**Comment by Serhioromano** [comment]
Thank you. Now everything is fine.

**Pull request merged**
