### PR TITLE
Probably better show full event in before_time instead a part of event in all_day

### PR DESCRIPTION
**Pull request by AleksSem**

### CODE REVIEW

**Comment by Serhioromano** [comment]
Why?

**Comment by AleksSem** [comment]
Sorry my fault, probably this would preferable just in my case.

Otherwise it`s hard to determine if there are any events which starts before time_start and wont able to resize calendar times automatically to show this event as full.

**Comment by Serhioromano** [comment]
The point is to show all events that are within given period or end of event or start of event within the period too. So we do not see when it starts maybe but we see that it ends here. 

What do you think?

**Comment by AleksSem** [comment]
Yes you absolutely right. 
In my case i need somehow determine if all events fits inside time range. If not i resize time range to display all events properly.
I`ll already find solution to fix this with small extension.

**Comment by Serhioromano** [comment]
Yuo can extend it with parameter if you want. Create a special parameter to show events that only fit the day or all that cross the day. I can accept that PR.

**Pull request closed without merging**
